config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  root "boards#index"

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  
  def index
    @boards = current_user.boards
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private
  def board_params
    params.require(:board).permit(:name)
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = @board.lists
  end

  def show
  end

  def new
    @list = @board.lists.new
  end
  
  def create
    @list = @board.lists.new(list_params)
    if @list.save
      redirect_to board_lists_path(@board)
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path(@board)
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end

  def set_board
    @board = Board.find(params[:board_id])

  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = @list.tasks
  end

  def show
  end

  def new
    @task = @list.tasks.new
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to board_lists_path(@list.board, @list.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @task.destroy
    redirect_to board_lists_path(@list.board, @list.id)
  end

  private
  def task_params
    params.require(:task).permit(:name)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<h1>Boards</h1>
<hr />

<div class= "ui centered card">
  <div class "content">
    <div class = "center aligned header b_title"><h2>YOUR BOARDS</h2></div>
      <% @boards.each do |b| %>
        <li class = "center aligned description">
            <%= link_to b.name, board_path(b), class: "b_name" %><%= button_to "Delete Board", b, method: :delete, class: "d_btn" %> 
            <br />
        </li>
      <% end %>
      </div>
      <%= link_to "Create New Board", new_board_path, class: "ui green bottom attached button" %> 
</div>

app/views/boards/new.html.erb
<h1>Create A Board</h1>
<%= form_with(model: @board, local: true,class: "ui form") do |f| %>
<div class = "field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name of Board" %>
</div>
<%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<div class="ui card">
  <div class="content">
    <p class="header">
      <%= @board.name %> 
    </p>
  </div>
  <div class="extra content">
    <%= link_to 'Edit', edit_board_path(@board) %> |
    <%= link_to "View Lists", board_lists_path(@board) %> |
    <%= link_to 'Back', boards_path %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <%= link_to "Boards", boards_path, class: "item" %>
  <%= link_to "Add Board", new_board_path, class: "item" %>
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tollol</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1><%= @board.name %></h1>
<hr />
<%= link_to "Create a New List", new_board_list_path(@board), class: "ui green button"%>
<br />
<br />
<div class = "ui three column grid">
  <% @lists.each do |l| %>
    <div class = "column">
      <div class = "ui fluid card">
        <div class = "card">
          <div class = "content">
              <h2 class = "center aligned header"><%= l.name %></h2>
              <div class = "description">
                <% l.tasks.each do |t| %>  
                <li class = "t_name">
                  <%= t.name %><br /><%= button_to "Delete Task", [l, t], method: :delete, class: "t_btn" %> 
                </li>
                <% end %>
              </div>
          </div>
          <%= link_to "Add Task", new_list_task_path(l), class: "ui buttom attached button" %>
          <%= link_to "Delete LIST", [@board, l], method: :delete, class: "ui red buttom attached button" %>
        </div>
      </div>
    </div> 
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Add a New list</h1>
<%= form_with(model: [@board, @list], local: true, class: "ui form") do |f| %>
<div class = "field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name of list" %>
</div>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="ui card">
<div class="ui card">
<div class="content">
  <p class="header">
    <%= @list.name %> 
  </p>
</div>
<div class="extra content">
    <%= link_to 'Edit', edit_list_path(@list) %> |
    <%= link_to "View Tasks", list_tasks_path(@list) %> |
    <%= link_to 'Back', lists_path %>
  </div>
</div> 













# <div class="content">
#     <p class="header">
#       <%= @list.name %> 
#     </p>
#   </div>
#   <div class="extra content">
#     <%= link_to 'Edit', edit_list_path(@list) %> |
#     <%= link_to "View Tasks", list_tasks_path(@list) %> |
#     <%= link_to 'Back', lists_path %>
#   </div>
# </div>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Add Some Tasks to Your List</h1>
<%= form_with(model: [@list, @task], local: true, class: "ui form") do |f| %>
<div class = "field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name of task" %>
</div>
<%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>